node {
    def mvnHome

    stage('Preparation') {
        git branch: 'main', url: 'https://github.com/clark-ewerton/selenium-java-testng-grid-docker-jenkins-allure.git'
    }

    stage('Build') {
        sh "mvn clean package -DskipTests=true"
    }

    stage('Test Execution') {
        try {
            sh "mvn test -Pweb-execution -Dsuite=selenium-grid -Dtarget=selenium-grid -Dheadless=true -Dbrowser=chrome"
        } catch (Exception e) {
            currentBuild.result = 'FAILURE'
        } finally {
            junit '**/target/surefire-reports/TEST-*.xml'

            /*
             * Please read https://wiki.jenkins.io/display/JENKINS/Configuring+Content+Security+Policy
             * to allow Jenkins to load static files
             */
            publishHTML (target: [
                allowMissing: false,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: 'target/surefire-reports',
                reportFiles: 'index.html',
                reportName: "TestNG Report"
            ])
        }
    }
}
